### ISSUE TITLE
Typeahead Functionality

### ISSUE THREAD

**Issue by brenthaertlein** [staticsound/moviechallenge#1]
Issue created.

/001_typeahead-functionality

**Comment by brenthaertlein** [comment]
### Description

As a user, typeahead returns back a movie title and other information, but when selected only populates the field with the movie title.

**Comment by ShortWaveLengthSubset** [comment]
[ ] Fuck someone's mother.

**Comment by brenthaertlein** [comment]
### Sub Tasks
- [x] Typeahead should fit the width of the search bar.
- [x] Typeahead should return a limited number of results.
- [x] Typeahead returns the movie year.
- [x] Typeahead returns the movie poster.

~~Typeahead results should be cached.~~

**Comment by brenthaertlein** [comment]
Branch created.

**Comment by brenthaertlein** [comment]
Merged into develop, ready for testing.

**Comment by johngreedjr** [comment]
There is an error where once you've selected a movie by clicking a result in typeahead it won't actually save the full value unless you click back into the field and then away. For example if I type in "Crit" and then click "Critters" it will appear in the field yet when I go to the main page it'll be saved as "Crit".

**RESOLVED**
