### ISSUE TITLE
Update Database Only When Models Change

### ISSUE THREAD

**Issue by brenthaertlein** [staticsound/moviechallenge#3]
Issue created.

**Comment by brenthaertlein** [comment]
### Description

As a developer, the database should only receive REST calls when the model has changed on the front end.

**Comment by brenthaertlein** [comment]
### Sub Tasks
- [x] Build basic error handling to prevent additional REST calls when the model is unchanged.

**Comment by johngreedjr** [comment]
Was handled on 004 branch.

**Comment by johngreedjr** [comment]
Ready for code review.
