### ISSUE TITLE
Prevent Any Field Being Submitted While Empty

### ISSUE THREAD

**Issue by brenthaertlein** [staticsound/moviechallenge#5]
Issue created.

**Comment by brenthaertlein** [comment]
### Description

As a user, be unable to submit fields that are empty.

As a developer, prevent the model from updating with 'null' or blank fields.

**Comment by brenthaertlein** [comment]
### Sub Tasks
- [x] Prevent model from updating null fields.
- [x] Prevent model from updating with blank fields.
- [x] Display a placeholder in lists for empty fields.

**Comment by johngreedjr** [comment]
still working through bug with challenge submit.

**Comment by johngreedjr** [comment]
Issue tested and closed.
